### PR TITLE
Rho 2

### PR DESCRIPTION
**Pull request by karthikhhr**

### CODE REVIEW

**Comment by jmrodri** [comment]
Why did we remove the Makefile?

**Comment by jmrodri** [comment]
What is the plan for rho 2? High level explanation would be helpful.

**Comment by cnsnyder** [comment]
Please open this PR against the rho-2 branch.

**Comment by cnsnyder** [comment]
@jmrodri The high level plan is to replicate the fact gathering functionality of rho using ansible playbooks and modules (where necessary)

**Pull request closed without merging**
